import { readFileSync, readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

function extractSourceMapFiles(html) {
  const re = /window\.__sourceMap\s*=\s*(\{[\s\S]*?\});?\s*<\/script>/;
  const match = html.match(re);
  if (!match) return [];

  try {
    const sourceMap = JSON.parse(match[1]);
    const files = new Set();
    for (const entry of Object.values(sourceMap)) {
      if (entry.file && typeof entry.file === 'string') {
        files.add(entry.file);
      }
    }
    return [...files];
  } catch {
    return [];
  }
}

export function pack(projectDir) {
  const resolved = resolve(projectDir);
  const viewsDir = join(resolved, '.codeindex', 'views');

  if (!existsSync(viewsDir)) {
    console.error(`Error: .codeindex/views/ not found in ${resolved}`);
    console.error('Make sure the project has been analyzed first.');
    process.exit(1);
  }

  const htmlFiles = readdirSync(viewsDir).filter(f => f.endsWith('.html'));

  if (htmlFiles.length === 0) {
    console.error('Error: No HTML files found in .codeindex/views/');
    process.exit(1);
  }

  // Collect all unique source file paths across all HTMLs
  const allFiles = new Set();
  for (const htmlFile of htmlFiles) {
    const html = readFileSync(join(viewsDir, htmlFile), 'utf-8');
    for (const file of extractSourceMapFiles(html)) {
      allFiles.add(file);
    }
  }

  if (allFiles.size === 0) {
    console.error('Error: No sourceMap entries found in HTML files');
    process.exit(1);
  }

  console.log(`Found ${allFiles.size} unique source files referenced across ${htmlFiles.length} HTML files.`);

  // Read each source file
  const sources = {};
  let packedCount = 0;
  let missingCount = 0;

  for (const relPath of allFiles) {
    const fullPath = join(resolved, relPath);
    if (existsSync(fullPath)) {
      try {
        sources[relPath] = readFileSync(fullPath, 'utf-8');
        packedCount++;
      } catch {
        console.warn(`  Skipped (read error): ${relPath}`);
        missingCount++;
      }
    } else {
      console.warn(`  Skipped (not found): ${relPath}`);
      missingCount++;
    }
  }

  // Write runtime JS
  const assetsDir = join(viewsDir, 'assets');
  if (!existsSync(assetsDir)) {
    mkdirSync(assetsDir, { recursive: true });
  }

  const json = JSON.stringify(sources);
  const runtime = `// Generated by codeindex-pack — standalone source code runtime
window.__codeindexSources = ${json};
`;

  const outPath = join(assetsDir, 'codeindex-runtime.js');
  writeFileSync(outPath, runtime);

  console.log(`\nPacked ${packedCount} source files into codeindex-runtime.js`);
  if (missingCount > 0) {
    console.log(`${missingCount} file(s) skipped (not found or unreadable)`);
  }
  console.log(`Output: ${outPath}`);
  console.log(`Total size: ${(Buffer.byteLength(runtime) / 1024).toFixed(1)} KB`);
  console.log('\nThe report now works on any static hosting without local files.');
}
